// Pure formatters that turn the computed run data into the review artifacts
// (manifest.json, full.diff, changes.json, REVIEW.md, REVIEW.html). Nothing in this module does
// I/O — scripts/dogfood/run.ts writes the strings these functions return.
import { createHash } from "node:crypto";
import { AGGREGATE_HASH_ALGORITHM_DESCRIPTION, type CorpusManifest } from "./corpus.js";
import { escapeNotable, type EditMark } from "./diff.js";
import type { EvidenceBlock } from "./evidence-hash.js";
import type { ImplementationInputsManifest } from "./implementation-inputs.js";
import type { FileResult } from "./transform-corpus.js";

/** Deterministic anchor for a `ReviewChange`, used identically by REVIEW.md (`<a id="...">`) and
 * REVIEW.html (element id + `#fragment` navigation) so a link generated by either side always
 * resolves. Derived purely from the review change's own content-stable id via SHA-256, truncated
 * -- this sidesteps every "which characters need URL/HTML escaping" question a raw path/id could
 * raise (a file path or hash suffix could in principle contain characters unsafe in an HTML id or
 * URL fragment): the anchor itself is always exactly `rc-` followed by 16 lowercase hex digits,
 * regardless of what the source id contains. Collision probability at this corpus's scale (order
 * 10^4 ids) against a 64-bit space is negligible; `checkAnchorsUnique` (consistency.ts) still
 * verifies no collision actually occurred rather than trusting this. */
export function reviewChangeAnchor(id: string): string {
  return `rc-${createHash("sha256").update(id).digest("hex").slice(0, 16)}`;
}

export interface RunProvenance {
  argv: string[];
  corpusRoot: string;
  outDir: string;
  locale: string;
  localeRationale: string;
  mode: string;
  dialect: string;
  nodeVersion: string;
  packageVersion: string;
  specVersion: string;
  gitHead: string;
  gitDirty: boolean;
}

export interface ManifestInput {
  provenance: RunProvenance;
  implementationInputs: ImplementationInputsManifest;
  corpusPreRun: CorpusManifest;
  corpusPostRun: CorpusManifest;
  corpusManifestsEqual: boolean;
  results: readonly FileResult[];
  counts: {
    changedFileCount: number;
    unchangedFileCount: number;
    errorCount: number;
    unifiedDiffHunkCount: number;
    /** The minimal, non-overlapping machine-level edit count -- see scripts/dogfood/diff.ts's
     * `AtomicEdit`. Always >= `reviewChangeCount` (a `ReviewChange` groups one or more). */
    atomicEditCount: number;
    /** The human review-unit count -- see scripts/dogfood/diff.ts's `ReviewChange`. This, not
     * `unifiedDiffHunkCount` and not `atomicEditCount`, is what `REVIEW.md` lists one row per. */
    reviewChangeCount: number;
  };
  idempotencyFailures: readonly string[];
  /** `null` for the counts-only manifest built before REVIEW.html/evidenceReviewHash exist (used
   * internally to render REVIEW.md's own summary section) -- the manifest actually written to disk
   * always supplies this. */
  evidence: EvidenceBlock | null;
}

export const REVIEW_STATE = "pending-human-review" as const;

export function buildManifest(input: ManifestInput): object {
  const idempotencyChecked = input.results.filter((r) => r.status !== "error").length;
  return {
    tool: "polytypo dogfood:m4",
    command: {
      argv: input.provenance.argv,
      corpus: input.provenance.corpusRoot,
      out: input.provenance.outDir,
      locale: input.provenance.locale,
      localeRationale: input.provenance.localeRationale,
      mode: input.provenance.mode,
      dialect: input.provenance.dialect,
    },
    node: { version: input.provenance.nodeVersion },
    package: { version: input.provenance.packageVersion },
    spec: { version: input.provenance.specVersion },
    git: { head: input.provenance.gitHead, dirty: input.provenance.gitDirty },
    implementationInputs: {
      note:
        "The dirty worktree's current bytes, not merely Git HEAD — every file listed below was read " +
        "directly off disk, including uncommitted and gitignored-but-present files, exactly as this " +
        "run imported them.",
      roots: input.implementationInputs.roots,
      aggregateHashAlgorithm: AGGREGATE_HASH_ALGORITHM_DESCRIPTION,
      fileCount: input.implementationInputs.fileCount,
      totalBytes: input.implementationInputs.totalBytes,
      aggregateHash: input.implementationInputs.aggregateHash,
      files: input.implementationInputs.files,
    },
    corpus: {
      root: input.provenance.corpusRoot,
      aggregateHashAlgorithm: AGGREGATE_HASH_ALGORITHM_DESCRIPTION,
      preRun: {
        fileCount: input.corpusPreRun.fileCount,
        totalBytes: input.corpusPreRun.totalBytes,
        aggregateHash: input.corpusPreRun.aggregateHash,
        files: input.corpusPreRun.files,
      },
      postRun: {
        fileCount: input.corpusPostRun.fileCount,
        totalBytes: input.corpusPostRun.totalBytes,
        aggregateHash: input.corpusPostRun.aggregateHash,
      },
      byteIdenticalBeforeAndAfter: input.corpusManifestsEqual,
    },
    results: {
      fileCount: input.results.length,
      changedFileCount: input.counts.changedFileCount,
      unchangedFileCount: input.counts.unchangedFileCount,
      errorCount: input.counts.errorCount,
      unifiedDiffHunkCount: input.counts.unifiedDiffHunkCount,
      atomicEditCount: input.counts.atomicEditCount,
      reviewChangeCount: input.counts.reviewChangeCount,
      idempotency: {
        checked: idempotencyChecked,
        failed: input.idempotencyFailures.length,
        failedPaths: [...input.idempotencyFailures],
      },
    },
    reviewState: REVIEW_STATE,
    evidence: input.evidence,
  };
}

export interface ReviewChangeEntry {
  id: string;
  /** Stable, opaque, URL/HTML-id-safe anchor for this row -- see `reviewChangeAnchor`. Identical
   * across REVIEW.md and REVIEW.html so a link generated by either always resolves. */
  anchor: string;
  path: string;
  diffHunkId: string;
  atomicEditIds: string[];
  oldOffset: { codePointStart: number; codePointEnd: number; byteStart: number; byteEnd: number };
  newOffset: { codePointStart: number; codePointEnd: number; byteStart: number; byteEnd: number };
  oldLineCol: { start: { line: number; column: number }; end: { line: number; column: number } };
  newLineCol: { start: { line: number; column: number }; end: { line: number; column: number } };
  before: string;
  after: string;
  beforeEscaped: string;
  afterEscaped: string;
  notableCodePoints: { codePoint: string; name: string; count: number }[];
  codePointDelta: { kind: string; from?: string; to?: string }[] | null;
  crossLineEdit: boolean;
  oldMarks: EditMark[];
  newMarks: EditMark[];
  riskTags: { tag: string; evidence: unknown }[];
  previewOldLeading: { text: string; truncated: boolean };
  previewOldTrailing: { text: string; truncated: boolean };
  previewIsolatedLeading: { text: string; truncated: boolean };
  previewIsolatedTrailing: { text: string; truncated: boolean };
  quotePairing:
    | { status: "paired"; role: "opening" | "closing"; pairedReviewChangeId: string }
    | { status: "unpaired" | "unknown" }
    | null;
  attribution: {
    overlappingIsolatedRules: string[];
    category: string;
    singleRule: string | null;
    composingRules: string[] | null;
    inferred: true;
  } | null;
}

/** Every changed file's every `ReviewChange`, flattened into one array — this is changes.json's
 * content. Order: files in discovery order, review changes within a file in ascending old-offset
 * order (already the order `computeFileDiff` returns them in). */
export function buildReviewChangeEntries(results: readonly FileResult[]): ReviewChangeEntry[] {
  const entries: ReviewChangeEntry[] = [];
  for (const result of results) {
    if (result.status !== "changed" || !result.diff) continue;
    for (const rc of result.diff.reviewChanges) {
      const attribution = result.attribution?.get(rc.id) ?? null;
      const riskTags = result.riskTags?.get(rc.id) ?? [];
      entries.push({
        id: rc.id,
        anchor: reviewChangeAnchor(rc.id),
        path: result.path,
        diffHunkId: rc.diffHunkId,
        atomicEditIds: rc.atomicEditIds,
        oldOffset: rc.oldOffset,
        newOffset: rc.newOffset,
        oldLineCol: rc.oldLineCol,
        newLineCol: rc.newLineCol,
        before: rc.before,
        after: rc.after,
        beforeEscaped: rc.beforeEscaped,
        afterEscaped: rc.afterEscaped,
        notableCodePoints: rc.notableCodePoints,
        codePointDelta: rc.codePointDelta,
        crossLineEdit: rc.crossLineEdit,
        oldMarks: rc.oldMarks,
        newMarks: rc.newMarks,
        riskTags: riskTags.map((t) => ({ tag: t.tag, evidence: t.evidence })),
        previewOldLeading: rc.previewOldLeading,
        previewOldTrailing: rc.previewOldTrailing,
        previewIsolatedLeading: rc.previewIsolatedLeading,
        previewIsolatedTrailing: rc.previewIsolatedTrailing,
        quotePairing: result.quotePairing?.get(rc.id) ?? null,
        attribution: attribution
          ? {
              overlappingIsolatedRules: attribution.overlappingIsolatedRules,
              category: attribution.category,
              singleRule: attribution.singleRule,
              composingRules: attribution.composingRules,
              inferred: true,
            }
          : null,
      });
    }
  }
  return entries;
}

/** full.diff's content: every changed file's ordinary unified diff, concatenated in deterministic
 * path order. This is a plain unified diff for general review/tooling — `ReviewChange` is a
 * separate, finer-grained view of the same underlying comparison, not a replacement for it. */
export function buildFullDiff(results: readonly FileResult[]): string {
  return results
    .filter((r) => r.status === "changed" && r.diff)
    .map((r) => r.diff!.unifiedText)
    .join("");
}

function pluralCount(n: number, noun: string): string {
  return `${n} ${noun}${n === 1 ? "" : "s"}`;
}

function attributionLabel(entry: ReviewChangeEntry): string {
  if (!entry.attribution) return "unattributed (no rule isolation performed)";
  const a = entry.attribution;
  switch (a.category) {
    case "single-rule":
      return a.singleRule ?? "unknown";
    case "multi-rule-composition":
      return `multi-rule-composition (${(a.composingRules ?? []).join("+")})`;
    case "interaction-candidate":
      return `interaction-candidate (${a.overlappingIsolatedRules.join("+") || "none"})`;
    case "ambiguous":
      return `ambiguous (${a.overlappingIsolatedRules.join("+") || "none"})`;
    case "unknown":
    default:
      return "unknown";
  }
}

function tokenEvidenceText(evidence: unknown): string {
  if (!evidence || typeof evidence !== "object") return "";
  const e = evidence as { tokenText?: string; distance?: number; boundaryType?: string };
  if (typeof e.tokenText === "string") return ` (token: ${mdCodeSpan(e.tokenText)})`;
  if (typeof e.distance === "number")
    return ` (${e.distance} code point(s) from ${mdCodeSpan(e.boundaryType ?? "?")})`;
  return "";
}

// ---------------------------------------------------------------------------------------------
// Markdown-table-safe rendering. GFM table cells cannot contain a literal `|` or a real newline
// regardless of code-span nesting, and a code span's own fence must be longer than any backtick
// run already inside the content it wraps (CommonMark's rule) or the span breaks. Rather than try
// to out-escape every renderer's edge cases, notable structural characters that would otherwise
// break the table are replaced with a distinct, clearly-labelled visible symbol -- this can never
// silently corrupt table structure, in any renderer, and the substitution is documented once in
// the checklist's legend rather than re-derived per cell.
// ---------------------------------------------------------------------------------------------

const TABLE_PIPE_MARKER = "❘"; // U+2758 LIGHT VERTICAL BAR, stands in for a literal "|"
const TABLE_NEWLINE_MARKER = "⏎"; // U+23CE RETURN SYMBOL, stands in for a literal line break

/** Makes `text` safe to place inside one GFM table cell, wrapped in an inline code span whose
 * fence is long enough that no backtick run already inside `text` can prematurely close it. */
function mdCodeSpan(text: string): string {
  const safe = text.replaceAll("|", TABLE_PIPE_MARKER).replaceAll("\n", TABLE_NEWLINE_MARKER);
  const longestBacktickRun = Math.max(0, ...(safe.match(/`+/g) ?? []).map((s) => s.length));
  const fence = "`".repeat(longestBacktickRun + 1);
  const needsPadding = safe.startsWith("`") || safe.endsWith("`") || safe === "";
  const padded = needsPadding ? ` ${safe} ` : safe;
  return `${fence}${padded}${fence}`;
}

/** Escapes `text` for use in an ordinary (non-code-span) Markdown table cell -- used for plain
 * labels, not for exact source/output content (which always goes through `mdCodeSpan` instead so
 * it is visibly delimited and never mistaken for prose). */
function mdPlainCell(text: string): string {
  return text.replaceAll("|", TABLE_PIPE_MARKER).replaceAll("\n", TABLE_NEWLINE_MARKER);
}

/** Splits `text` into contiguous segments according to `marks` (window-relative code-point
 * ranges, ascending, non-overlapping -- as `ReviewChange.oldMarks`/`newMarks` are constructed).
 * A single-edit item yields exactly one `marked: true` segment spanning the whole text; a
 * multi-edit item yields one marked segment per edit, with any unmarked (unchanged) text between
 * them as separate `marked: false` segments -- so each edit is individually highlighted rather
 * than one envelope over the whole group (task item 1's multi-atomic requirement). */
function segmentsFromMarks(
  text: string,
  marks: readonly EditMark[],
): { text: string; marked: boolean }[] {
  const cps = [...text];
  const segments: { text: string; marked: boolean }[] = [];
  let cursor = 0;
  for (const m of marks) {
    if (m.start > cursor)
      segments.push({ text: cps.slice(cursor, m.start).join(""), marked: false });
    segments.push({ text: cps.slice(m.start, m.end).join(""), marked: true });
    cursor = m.end;
  }
  if (cursor < cps.length) segments.push({ text: cps.slice(cursor).join(""), marked: false });
  return segments;
}

/** Renders `text` (a `ReviewChange`'s `before` or `after`) as a sequence of Markdown-table-safe
 * code spans, wrapping each individually-marked edit span in `**[…]**`. Each segment is escaped
 * for notable code points independently (not by slicing a precomputed whole-string escaped view,
 * whose length differs from the raw text once any watch-listed code point expands to a bracketed
 * token) and passed through `mdCodeSpan` on its own, so one segment's embedded backtick never
 * forces every other segment's fence wider than it needs to be. */
function renderMarkedText(text: string, marks: readonly EditMark[]): string {
  return segmentsFromMarks(text, marks)
    .map((seg) => {
      const escaped = escapeNotable(seg.text).escaped;
      const cell = mdCodeSpan(escaped !== seg.text ? escaped : seg.text);
      return seg.marked ? `**[**${cell}**]**` : cell;
    })
    .join("");
}

/** Renders one side's complete preview phrase: `leading + <marked text> + trailing`. An ellipsis
 * prefix/suffix marks real truncation. `text`/`marks` is either (`before`, `oldMarks`) for
 * `sourcePreview` or (`after`, `newMarks`) for `isolatedAfterPreview` -- see `ReviewChange`'s doc
 * comment in diff.ts for what distinguishes the two. */
function renderPreviewSide(
  leading: { text: string; truncated: boolean },
  text: string,
  marks: readonly EditMark[],
  trailing: { text: string; truncated: boolean },
): string {
  const leadingCell = leading.text ? mdCodeSpan(leading.text) : "";
  const trailingCell = trailing.text ? mdCodeSpan(trailing.text) : "";
  const leadingEllipsis = leading.truncated ? "…" : "";
  const trailingEllipsis = trailing.truncated ? "…" : "";
  return `${leadingEllipsis}${leadingCell}${renderMarkedText(text, marks)}${trailingCell}${trailingEllipsis}`;
}

/** REVIEW.md's content — a human-review checklist, not a verdict. Every `ReviewChange` id is
 * listed exactly once, each with an `UNREVIEWED` decision slot. Groups changes by file with an
 * anchor per file so a 10,000-row ledger stays navigable; full per-change detail (exact
 * before/after, escaped view, code-point delta, risk-tag evidence) is inline in the table itself,
 * not deferred to changes.json only — a reviewer must be able to work from this file alone. */
export function buildReviewMarkdown(
  manifestData: object,
  entries: readonly ReviewChangeEntry[],
  results: readonly FileResult[],
): string {
  const manifest = manifestData as {
    command: {
      locale: string;
      localeRationale: string;
      mode: string;
      dialect: string;
      corpus: string;
    };
    results: {
      changedFileCount: number;
      unchangedFileCount: number;
      errorCount: number;
      unifiedDiffHunkCount: number;
      atomicEditCount: number;
      reviewChangeCount: number;
      idempotency: { checked: number; failed: number };
    };
    git: { head: string; dirty: boolean };
    evidence: EvidenceBlock | null;
  };

  const byAttribution = new Map<string, number>();
  const byTag = new Map<string, number>();
  const byFile = new Map<string, number>();
  for (const entry of entries) {
    byFile.set(entry.path, (byFile.get(entry.path) ?? 0) + 1);
    byAttribution.set(
      attributionLabel(entry),
      (byAttribution.get(attributionLabel(entry)) ?? 0) + 1,
    );
    const tags =
      entry.riskTags.length > 0 ? entry.riskTags.map((t) => t.tag) : ["no-high-risk-tag"];
    for (const tag of tags) byTag.set(tag, (byTag.get(tag) ?? 0) + 1);
  }

  const errors = results.filter((r) => r.status === "error");
  const idempotencyFailed = results.filter(
    (r) => r.status !== "error" && r.idempotencyOk === false,
  );

  const lines: string[] = [];
  lines.push("# M4 Dogfooding Review Checklist");
  lines.push("");
  lines.push(
    "**Recommended interface: `REVIEW.html`**, in this same bundle directory -- a self-contained, " +
      "local, filterable/searchable per-change viewer with a Previous/Next flow and its own decision " +
      "tracking. Open it directly in a browser (`file://`). This file (`REVIEW.md`) remains the " +
      "canonical, portable index: the complete id list, the same isolated previews and pair links, " +
      "plain text/JSON tooling can read it, and it is what `changes.json`'s consistency checks " +
      "verify against. Neither replaces the other.",
  );
  lines.push("");
  lines.push(
    "**An agent's automated classification cannot satisfy M4.** Every tag, count, and rule " +
      "attribution in this bundle is a hint for where to look — none of it is a substitute for the " +
      "author reading each change.",
  );
  lines.push("");
  lines.push(
    "**M4 remains blocked until the author reviews every change below and there are zero `REJECT` " +
      "decisions.** This file's current state proves nothing was reviewed yet: every decision below is `UNREVIEWED`.",
  );
  lines.push("");
  lines.push(
    "**Review unit and granularity.** Each row below is a `ReviewChange`: one or more related " +
      "`AtomicEdit`s (the minimal, non-overlapping machine-level diff spans -- see `atomicEditIds`), " +
      "grouped by a documented adjacency rule (nearby edits on the same line merge; a genuine " +
      "multi-line merge/split never merges with a neighbour; a size cap forces a deterministic " +
      "split) into one reviewable unit. It is not a `full.diff` unified hunk, which can bundle many " +
      "unrelated edits under one context window. **The machine span itself is often exactly one " +
      "code point** (an apostrophe, a quote mark, a dash) -- that is the correct minimal, provably " +
      "non-overlapping unit for reconstruction and attribution, and this tool does not force it " +
      "wider just to shrink the row count. Readability instead comes from the **Preview** column.",
  );
  lines.push("");
  lines.push(
    "**Preview (sourcePreview → isolatedAfterPreview).** The left side of the arrow is the real " +
      "surrounding word/phrase from the ORIGINAL file, independently rebuilt from source text at " +
      "this row's own offsets. The right side is the SAME logical window with ONLY this row's own " +
      "edit(s) applied -- never the full pipeline output, which could (and on earlier drafts of " +
      "this tool did) silently show an unrelated neighbouring row's own edit inside the same " +
      "preview window. Each individual edit is marked `**[…]**` (a multi-edit row marks every edit " +
      "separately, not one envelope over the whole row). A leading/trailing `…` means real content " +
      `was trimmed at that side. A literal \`|\` in preview text is shown as "${TABLE_PIPE_MARKER}" ` +
      `and a real line break as "${TABLE_NEWLINE_MARKER}" -- Markdown table cells cannot contain ` +
      "either. Preview text is never used for reconstruction, coverage, or attribution.",
  );
  lines.push("");
  lines.push("## Run summary");
  lines.push("");
  lines.push(`- Corpus: \`${manifest.command.corpus}\``);
  lines.push(
    `- Locale / mode / dialect: \`${manifest.command.locale}\` / \`${manifest.command.mode}\` / \`${manifest.command.dialect}\``,
  );
  if (manifest.command.localeRationale) {
    lines.push(`- Locale rationale: ${manifest.command.localeRationale}`);
  }
  lines.push(
    `- Git HEAD: \`${manifest.git.head}\`${manifest.git.dirty ? " (dirty worktree — see manifest.json implementationInputs for the actual bytes used)" : ""}`,
  );
  lines.push(
    `- Files: ${pluralCount(manifest.results.changedFileCount + manifest.results.unchangedFileCount + manifest.results.errorCount, "file")} — ` +
      `${manifest.results.changedFileCount} changed, ${manifest.results.unchangedFileCount} unchanged, ${pluralCount(manifest.results.errorCount, "error")}`,
  );
  lines.push(`- Unified diff hunks (\`full.diff\`): ${manifest.results.unifiedDiffHunkCount}`);
  lines.push(`- Atomic edits (minimal machine-level spans): ${manifest.results.atomicEditCount}`);
  lines.push(`- Review changes (this checklist's rows): ${manifest.results.reviewChangeCount}`);
  lines.push(
    `- Idempotency: ${pluralCount(manifest.results.idempotency.checked, "file")} checked, ${pluralCount(manifest.results.idempotency.failed, "failure")}`,
  );
  lines.push(`- Review state: \`${REVIEW_STATE}\``);
  // `evidenceReviewHash` is deliberately NOT rendered inline here: it is derived in part from this
  // very file's own SHA-256 digest (see evidence-hash.ts's doc comment on hash-cycle avoidance),
  // so embedding it in this file's own content would be circular. It is written once, safely,
  // into manifest.json's `evidence.evidenceReviewHash` (computed after this file's final content
  // is known) and into REVIEW.html (generated after that, from the same value) -- see either for
  // the actual hash of this bundle.
  lines.push(
    "- Evidence review hash (`evidenceReviewHash`): see `manifest.json`'s `evidence.evidenceReviewHash` (and REVIEW.html's header) -- omitted from this file to avoid a hash depending on this file's own content.",
  );
  lines.push("");

  if (errors.length > 0) {
    lines.push("## Malformed input (transform failed)");
    lines.push("");
    for (const e of errors) {
      lines.push(`- \`${e.path}\`: ${e.errorCode ?? "error"} — ${e.errorMessage}`);
    }
    lines.push("");
  }

  if (idempotencyFailed.length > 0) {
    lines.push("## Idempotency failures");
    lines.push("");
    for (const f of idempotencyFailed) {
      lines.push(`- \`${f.path}\``);
    }
    lines.push("");
  }

  lines.push("## Counts by attribution (inferred — see changes.json)");
  lines.push("");
  lines.push(
    "`single-rule` is a confirmed exact reproduction by one isolated rule. `multi-rule-composition` " +
      "means the union of several rules' isolated edits, applied together unmodified, reproduces the " +
      "observed text -- i.e. these rules acted independently and simply co-occurred; it is *not* a " +
      "claim of interaction. `interaction-candidate` means the isolated edits overlap or their union " +
      "does not reproduce the observed text -- something changed when the rules ran together, but " +
      "this tool cannot prove which rule depends on which (the public API has no way to reorder " +
      "rules), so it is never asserted as a confirmed interaction. `ambiguous` means more than one " +
      "rule's isolated output alone exactly matches. `unknown` means no isolated rule touched this " +
      "region at all.",
  );
  lines.push("");
  for (const [label, count] of [...byAttribution.entries()].sort((a, b) => b[1] - a[1])) {
    lines.push(`- ${label}: ${pluralCount(count, "change")}`);
  }
  lines.push("");

  lines.push("## Counts by risk tag");
  lines.push("");
  lines.push(
    "Absence of a tag below means it was not observed in this corpus snapshot — not that the " +
      "underlying false-positive class is solved in general. Statistical grouping here is " +
      "navigation only; a group total is never a substitute for reviewing its individual rows.",
  );
  lines.push("");
  for (const [tag, count] of [...byTag.entries()].sort((a, b) => b[1] - a[1])) {
    lines.push(`- \`${tag}\`: ${pluralCount(count, "change")}`);
  }
  lines.push("");

  lines.push("## Counts by file");
  lines.push("");
  for (const [file, count] of [...byFile.entries()].sort((a, b) => (a[0] < b[0] ? -1 : 1))) {
    const anchor = file.replace(/[^a-zA-Z0-9]+/g, "-").toLowerCase();
    lines.push(`- [\`${mdPlainCell(file)}\`](#file-${anchor}): ${pluralCount(count, "change")}`);
  }
  lines.push("");

  lines.push("## Change checklist");
  lines.push("");
  lines.push(
    "Decision legend: `ACCEPT` / `REJECT` / `NEEDS-DISCUSSION`. Every row starts `UNREVIEWED`. " +
      "Every `ReviewChange` id below appears exactly once, each carrying a stable HTML anchor " +
      '(`<a id="rc-…">`) so it can be linked to directly. **Preview** is `sourcePreview → ' +
      "isolatedAfterPreview` -- see the note above the run summary. **Pair** is a real relative " +
      "link (`[closing ↔ `id`](#rc-…)`) to a quote mark's opening/closing counterpart, present " +
      "only when that link is proven from a simple, unambiguous same-line count (never a guess); " +
      "`unknown`/`unpaired` mean no such link could be proven, not that none exists. Opening and " +
      "closing always link to each other symmetrically.",
  );
  lines.push("");

  let currentFile: string | null = null;
  for (const entry of entries) {
    if (entry.path !== currentFile) {
      currentFile = entry.path;
      const fileAnchor = currentFile.replace(/[^a-zA-Z0-9]+/g, "-").toLowerCase();
      lines.push(`### File: \`${currentFile}\` {#file-${fileAnchor}}`);
      lines.push("");
      lines.push(
        "| ID | Line (old→new) | Preview (sourcePreview → isolatedAfterPreview) | Pair | Tags | Attribution | Decision | Note |",
      );
      lines.push("|---|---|---|---|---|---|---|---|");
    }
    const oldSide = renderPreviewSide(
      entry.previewOldLeading,
      entry.before,
      entry.oldMarks,
      entry.previewOldTrailing,
    );
    const newSide = renderPreviewSide(
      entry.previewIsolatedLeading,
      entry.after,
      entry.newMarks,
      entry.previewIsolatedTrailing,
    );
    const previewCell = `${oldSide} → ${newSide}`;
    const tagsCell =
      entry.riskTags.length > 0
        ? entry.riskTags
            .map((t) => `${mdCodeSpan(t.tag)}${tokenEvidenceText(t.evidence)}`)
            .join(", ")
        : "—";
    const oldLoc = `${entry.oldLineCol.start.line}:${entry.oldLineCol.start.column}`;
    const newLoc = `${entry.newLineCol.start.line}:${entry.newLineCol.start.column}`;
    const pairing = entry.quotePairing;
    const pairCell =
      pairing === null
        ? "—"
        : pairing.status === "paired"
          ? `${pairing.role} ↔ [${mdCodeSpan(pairing.pairedReviewChangeId)}](#${reviewChangeAnchor(pairing.pairedReviewChangeId)})`
          : pairing.status;
    // The ID cell must keep the exact `` <a id="..."></a>`id` `` shape -- checkReviewMarkdownIds's
    // parser in consistency.ts expects the code span (and only the code span) to hold the raw id.
    lines.push(
      `| <a id="${entry.anchor}"></a>\`${entry.id}\` | ${oldLoc}→${newLoc} | ${previewCell} | ${pairCell} | ${tagsCell} | ${attributionLabel(entry)} | UNREVIEWED | |`,
    );
  }
  lines.push("");

  return lines.join("\n") + "\n";
}
